// import java.util.Scanner;
public class string {
public static void main(String[] args) {
        // Scanner st = new Scanner(System.in);
        // System.out.print("Enter your name :");
        // String s1 = st.next();
        // System.out.println("hello " + s1 + " have good day");
        // String s1 = st.nextLine();
        // System.out.println(s1); 
        // String st1= new String("       Smit       ");
        // int l = st1.length();
        // System.out.println(st1);
        // System.out.println(l);
        // String l1 = st1.toLowerCase();
        // System.out.println(l1);
        // String l2 = st1.toUpperCase();
        // System.out.println(l2);
        // String l3 = st1.trim();
        // System.out.println(l3);
        // String st2= new String("Smit .");
        // String l4 = st2.substring(1, 3);
        // System.out.println(l4);
        // String l5 = st2.replace('S','V');
        // String l6 = l5.replace('i','s');
        // String l7 = l6.replace('m','i');
        // String l8 = l7.replace('t','h');
        // String l9 = l8.replace(' ','w');
        // String l10 = l9.replace('.','a');
        // System.out.println(st2);
        // System.out.println(l10);
        // System.out.println(l10.startsWith("Vi"));
        // System.out.println(l10.endsWith("wa"));
        // System.out.println(l10.charAt(2));
        // String l11 = new String("Vishwa");
        // int l12= l11.indexOf('s');
        // System.out.println(l12);
        // String l13 = new String("VishwaVishwa");
        // int l14= l13.indexOf('s', 3);
        // System.out.println(l14);
        // int l15= l13.lastIndexOf('s') ;
        // System.out.println(l15);
        // int l16= l13.lastIndexOf('s',6) ;
        // System.out.println(l16);
        // String l17 = new String("Vishwa");
        // System.out.println(l17.equals("vishwa"));
        // System.out.println(l17.equalsIgnoreCase("vishwa"));
        // String l18 = new String("Vishwa");
        // System.out.println("hello " + l18 + "\n \\ a \t a \' \"");
    }
}
